lsi: false
safe: true
#source: SebiSchlegel.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

domain: SebiSchlegel.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://sebastianschlegelmejia.com  # the base hostname and protocol for your site, e.g. http://example.com